### ISSUE TITLE
高度な設定のIndexError

### ISSUE THREAD

**Issue by Kusa938** [ogawa3427/risyu#8]

**Comment by Kusa938** [comment]
仕様でしたら申し訳ないです。
”高度な設定”をおすとException in Tkinter callbackとなります。IndexErrorとのことでしたので要素数や要素の有無についてご確認お願いします。

**Comment by ogawa3427** [comment]
すみません
急ぎ実装します

**Comment by ogawa3427** [comment]
https://github.com/ogawa3427/risyu/pull/9
ひとつつくりました
あとコードもきれいにしました
